### ISSUE TITLE
Not obtaining job status

### ISSUE THREAD

**Issue by halexand** [Snakemake-Profiles/generic#1]
Hello, 

I am trying out the generic profile and it has successfully scheduled jobs-- but it appears to not be successful in tracking job progress (see below error). No new jobs are activated after the jobs submitted to slurm complete-- presumably because the jobs are not noted as completed. 

Any thoughts on how to address this? 

Thanks!

```
scontrol_print_job error: Invalid job id specified
Traceback (most recent call last):
  File "/vortexfs1/home/hpcuser1/.config/snakemake/gen-slurm-2/slurm_status.py", line 27, in <module>
    state=parse_key_value(out)['JobState']
KeyError: 'JobState'
Submitted job 2792 with external jobid 'Submitted batch job 24243'.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/executors.py", line 719, in job_status
    shell=True).decode().split("\n")[0]
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/vortexfs1/home/hpcuser1/.config/snakemake/gen-slurm-2/slurm_status.py Submitted batch job 24234' returned non-zero ex
it status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/executors.py", line 754, in _wait_for_jobs
    status = job_status(active_job)
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/executors.py", line 730, in job_status
    raise WorkflowError("Failed to obtain job status. "
snakemake.exceptions.WorkflowError: Failed to obtain job status. See above for error message.
```

**Comment by SilasK** [comment]
To be sure: you are using slurm system. Can you give me a version? 
Apparently, there is a difference to the system I'm using. 

Can you give me the output of `scontrol show jobid <any jobid>` It should have `JobState=`in it. 

In the meantime, you may deactivate the status check by commenting the line `cluster-status:`

**Comment by halexand** [comment]
Hi @SilasK , 

Yes, I am using a slurm system-- the HPC is running slurm/17.11.2. 

The output of `scontrol show jobid` is the following. 

```
JobId=25837 JobName=TARA.download_fastq2.run=ERR599282
   UserId=hpcuser1(100405) GroupId=domain users(10000) MCS_label=N/A
   Priority=7417 Nice=0 Account=science QOS=unlim
   JobState=RUNNING Reason=None Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:00:53 TimeLimit=1-00:00:00 TimeMin=N/A
   SubmitTime=2018-11-30T10:46:01 EligibleTime=2018-11-30T10:46:01
   StartTime=2018-11-30T10:46:03 EndTime=2018-12-01T10:46:03 Deadline=N/A
   PreemptTime=None SuspendTime=None SecsPreSuspend=0
   LastSchedEval=2018-11-30T10:46:03
   Partition=compute AllocNode:Sid=poseidon-l1:102946
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=pn047
   BatchHost=pn047
   NumNodes=1 NumCPUs=1 NumTasks=1 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=1,mem=1G,node=1,billing=1
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=1 MinMemoryNode=1G MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   Gres=(null) Reservation=(null)
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/vortexfs1/omics/data/tara/tara-download-snakemake/.snakemake/tmp.9e09qbix/snakejob.download_fastq2.3080.sh
   WorkDir=/vortexfs1/omics/data/tara/tara-download-snakemake
   StdErr=/vortexfs1/omics/data/tara/tara-download-snakemake/slurm-25837.out
   StdIn=/dev/null
   StdOut=/vortexfs1/omics/data/tara/tara-download-snakemake/slurm-25837.out
   Power=
```
 The `JobState=` value is present-- so I am not sure what is going on.

**Comment by halexand** [comment]
One thought: the first line of the error is related to the jobid not being valid. Perhaps it is an issue with the parsing of the Snakemake output and it is trying to check with the wrong jobid number? 

```
scontrol_print_job error: Invalid job id specified
Traceback (most recent call last):
  File "/vortexfs1/home/hpcuser1/.config/snakemake/gen-slurm-2/slurm_status.py", line 27, in <module>
    state=parse_key_value(out)['JobState']
KeyError: 'JobState'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/executors.py", line 719, in job_status
    shell=True).decode().split("\n")[0]
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/vortexfs1/home/hpcuser1/.conda/envs/snakemake/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/vortexfs1/home/hpcuser1/.config/snakemake/gen-slurm-2/slurm_status.py Submitted batch job 25835' returned non-zero ex
it status 1.

```

**Comment by SilasK** [comment]
OK, the first line would indicate that `scontrol show jobid <invalid jobid>`, which messes up the rest. 
So, why the jobid is invalid? 

Do you get the log messages:
`Submitted job 558 with external jobid '11210388'`
with a correct job id?
Can you check the snakemake log file? It yould be somwhere in `workindir/.snakemake/logs`

**Comment by halexand** [comment]
So, I tried to dig around in the `slurm_status.py` script-- which I think might be the source of the issue as from above the error is:

```
/vortexfs1/home/hpcuser1/.config/snakemake/gen-slurm-2/slurm_status.py Submitted batch job 27207' returned non-zero exit status 1. 
```
I tried running this script directly on the command line: `slurm_status.py Submitted batch job 27207` which produced the following error: 
```
scontrol_print_job error: Invalid job id specified

Traceback (most recent call last)
    File "slurm_status.py", line 28, in <module>
        state=parse_key_value(out)['JobState']
KeyError: 'JobState'
```
If however I run: `slurm_status.py 27207` it works. 

So, I think the issue is the way that the Snakemake output is being passed to `slurm_status.py`-- the whole string and not just the numeric value is getting passed. 

I am not sure why this would be an issue on my system but not yours... any thoughts? I also had a hard time figuring out where the parsing of the Snakemake output happens.  

Thoughts?

**Comment by SilasK** [comment]
Yes,  I think you are right. can you send me your snakemake log file.

**Comment by halexand** [comment]
Hi @SilasK : 

I have been just working with a small test snakemake to test it out. Here is the log: 

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 20
Job counts:
        count   jobs
        1       all
        2       reads
        3

[Tue Dec  4 15:13:21 2018]
rule reads:
    output: reads/b.chr21.1.fq, reads/b.chr21.2.fq
    jobid: 2
    wildcards: sample=b, chrom=21

Submitted job 2 with external jobid 'Submitted batch job 27205'.

[Tue Dec  4 15:13:22 2018]
rule reads:
    output: reads/a.chr21.1.fq, reads/a.chr21.2.fq
    jobid: 1
    wildcards: sample=a, chrom=21

Submitted job 1 with external jobid 'Submitted batch job 27206'.
Terminating processes on user request, this might take some time.
Will exit after finishing currently running jobs.
Complete log: /vortexfs1/omics/data/test/ngs-test-data/.snakemake/log/2018-12-04T151320.997303.snakemake.log
```

I also ran Snakemake with the `--verbose` flag-- don't think this is helpful but I will pass it along anyway. 

```
Building DAG of jobs...
Checking status of 0 jobs.
Using shell: /usr/bin/bash
Provided cluster nodes: 20
Job counts:
        count   jobs
        1       all
        2       reads
        3
Resources before job selection: {'_cores': 9223372036854775807, '_nodes': 20}
Ready jobs (2):
        reads
        reads
Selected jobs (2):
        reads
        reads
Resources after job selection: {'_cores': 9223372036854775805, '_nodes': 18}

[Tue Dec  4 15:17:06 2018]
rule reads:
    output: reads/a.chr21.1.fq, reads/a.chr21.2.fq
    jobid: 2
    wildcards: sample=a, chrom=21

Jobscript:
#!/bin/sh
# properties = {"type": "single", "rule": "reads", "local": false, "input": [], "output": ["reads/a.chr21.1.fq", "reads/a.chr21.2.fq"], "wildcards": {"sample"
: "a", "chrom": "21"}, "params": {"url": "https://www.ebi.ac.uk/arrayexpress/files/E-GEUV-1/HG00096.1.M_111124_6.bam", "seed": 5617}, "log": [], "threads": 1,
 "resources": {}, "jobid": 2, "cluster": {"system": "slurm", "time": "300", "mem": "10", "threads": "8", "queue": "compute", "nodes": 1, "command_options": {"
slurm": {"command": "sbatch --parsable", "key_mapping": {"name": "--job-name={}", "threads": "-n {}", "mem": "--mem={}g", "account": "--account={}", "queue": 
"--partition={}", "time": "--time={}", "nodes": "-N {}"}}, "pbs": {"command": "qsub", "key_mapping": {"name": "-N {}", "account": "-W group_list={}", "queue":
 "-q {}", "nodes": "-l nodes={}", "threads": "ppn={}", "mem": "mem={}gb", "time": "walltime={}00"}}, "lsf": {"command": "bsub", "key_mapping": {"name": "-J {}
", "threads": "-n {}", "mem": "-M {}000000", "account": "-P {}", "queue": "-q {}", "time": "-W {}", "nodes": "-C {}"}}}}}
cd /vortexfs1/omics/data/test/ngs-test-data && \
/vortexfs1/home/hpcuser1/.conda/envs/snakemake/bin/python \
-m snakemake reads/a.chr21.2.fq --snakefile /vortexfs1/omics/data/test/ngs-test-data/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /vortexfs1/omics/data/test/ngs-test-data/.snakemake/tmp.s_g628eq /vortexfs1/omics/data/test/ngs-test-data/.snakemake/conda/76aa3eee --latency
-wait 5 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
   --nocolor \
--notemp --no-hooks --nolock --mode 2  --use-conda  --allowed-rules reads  && exit 0 || exit 1

Submitted job 2 with external jobid 'Submitted batch job 27207'.

[Tue Dec  4 15:17:07 2018]
rule reads:
    output: reads/b.chr21.1.fq, reads/b.chr21.2.fq
    jobid: 1
    wildcards: sample=b, chrom=21
Jobscript:
#!/bin/sh
# properties = {"type": "single", "rule": "reads", "local": false, "input": [], "output": ["reads/b.chr21.1.fq", "reads/b.chr21.2.fq"], "wildcards": {"sample": "b", "chrom": "21"}, "params": {"url": "https://www.ebi.ac.uk/arrayexpress/files/E-GEUV-1/HG00096.1.M_111124_6.bam", "seed": 5530}, "log": [], "threads": 1, "resources": {}, "jobid": 1, "cluster": {"system": "slurm", "time": "300", "mem": "10", "threads": "8", "queue": "compute", "nodes": 1, "command_options": {"slurm": {"command": "sbatch --parsable", "key_mapping": {"name": "--job-name={}", "threads": "-n {}", "mem": "--mem={}g", "account": "--account={}", "queue": "--partition={}", "time": "--time={}", "nodes": "-N {}"}}, "pbs": {"command": "qsub", "key_mapping": {"name": "-N {}", "account": "-W group_list={}", "queue": "-q {}", "nodes": "-l nodes={}", "threads": "ppn={}", "mem": "mem={}gb", "time": "walltime={}00"}}, "lsf": {"command": "bsub", "key_mapping": {"name": "-J {}", "threads": "-n {}", "mem": "-M {}000000", "account": "-P {}", "queue": "-q {}", "time": "-W {}", "nodes": "-C {}"}}}}}
cd /vortexfs1/omics/data/test/ngs-test-data && \
/vortexfs1/home/hpcuser1/.conda/envs/snakemake/bin/python \
-m snakemake reads/b.chr21.2.fq --snakefile /vortexfs1/omics/data/test/ngs-test-data/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /vortexfs1/omics/data/test/ngs-test-data/.snakemake/tmp.s_g628eq /vortexfs1/omics/data/test/ngs-test-data/.snakemake/conda/76aa3eee --latency-wait 5 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
   --nocolor \
--notemp --no-hooks --nolock --mode 2  --use-conda  --allowed-rules reads  && exit 0 || exit 1

Submitted job 1 with external jobid 'Submitted batch job 27208'.
Checking status of 2 jobs.
Terminating processes on user request, this might take some time.
Will exit after finishing currently running jobs.
Complete log: /vortexfs1/omics/data/test/ngs-test-data/.snakemake/log/2018-12-04T151705.708734.snakemake.log
unlocking
removing lock
removing lock
removed all locks

```

**Comment by SilasK** [comment]
Apparently, some slurm systems don't care about the `--parsable` flag and return 'Submitted batch job 27208' instead of just '27208'. 

I added a parsing step to get to the id. It should now work. You can download the profile again or just replace the scheduler.py

re-open the issue, if it doesn't work.

**Comment by halexand** [comment]
That is annoying about the slurm systems-- I can check with our sys admin about the `--parsable` flag. 

I re-downloaded the profile and ran it and am still getting the same error. I have double checked that the `schedule.py`  updated and it has. Just curious if perhaps the `jobid` isn't getting passed to the command ~line 54?

**Comment by SilasK** [comment]
You still get the 
`Submitted job 2 with external jobid 'Submitted batch job 27205'.`
in your logfile?

The jobid is the output of the command line in sheduler.py line 54. 
You can try to change the end of the sheduler.py  to the following code. 

```
else:
    res= output.decode("utf-8")
    import re
    m = re.search("Submitted batch job (\d+)", res)
    jobid = m.group(1)
    print(jobid)

```

**Comment by halexand** [comment]
Yes, it is still printing the following: 

`Submitted job 2 with external jobid 'Submitted batch job 27860'.`

I tried the new update to no success. Does jobid need to be added to another dictionary or the like?

**Comment by SilasK** [comment]
jobid only the nimber should be printed the end of the submitter script.
Which isn't taking up by snakemake, printed in the log and is available in
the surm_status.py. wgere it calls 'scontrol'.

Which crashes when the idea that correct.

Have you tried slurm profile?

**Comment by halexand** [comment]
Hi @SilasK -- 

I figured it out! I was coupling it with the `--cluster` flag in my test run by accident (didn't change my submission script. I added the `--parsable` flag to the `sbatch` command and it worked. 

Thanks for all the help!

**Comment by SilasK** [comment]
You are welcome, thanks for testing the profile.
